name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]  # 只在 main 分支 push 时触发
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:  # 新增权限配置
      contents: write  # 允许写入仓库
      pages: write    # 允许部署 Pages
      id-token: write  # 关键：允许生成 OIDC 令牌


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Install Cargo-bin
        run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      - name: Install Dioxus CLI
        run: cargo binstall dioxus-cli

      - name: Build Dioxus project (release mode)
        run: dx build --release
      
      - name: Verify build output
        run: ls -R ./target/dx/github_io/release/web/public

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./target/dx/github_io/release/web/public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4