name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]  # 只在 main 分支 push 时触发
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Dioxus CLI
        run: cargo install dioxus-cli

      - name: Build Dioxus project (release mode)
        run: dioxus build --release

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: ./target/dx/github_io/release/web/public  # 替换为 Dioxus 生成静态文件的目录（默认可能是 `dist` 或 `target/release/`）

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./target/dx/github_io/release/web/public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4